travis:
  secure:
    BINSTAR_TOKEN: oD9IJLAuauzvFMq5n2aDEGLh/fXvgs/fQhLv4TNJ+DDU6v3RIgAeBA/RW9vEi7BjVemRJ6jMn4Cq6Ntd1zw0HyntI3Win+SlRww+8AE4733o37TVfhR/otNefykRFAes42ywJ2cIt8s9uAtzgvRiQX3bACegOiB6wDHV7NuQNaQ463YAMNcz+zWL+uNFb6jov+QQ3sa8eNz3spfYEPWCTJAuZFDmg8iFZRs/FunyLt897lBf6CXsGTlEkfj6KlVGP/Nw26NNNjV8NGeNg1V6KNGGmb/1MG8Ph6gk25PE64rQfW2mYEOqBMrIt5Z5GDlgK0XRZHE0Z0BdzF+gniVg60SEvIb8pmCX9hLDhoxi8VpSZkI+QXpelJIKoDsxoiuDYre4zSMRP9EAhvcWpk274Jf9pI/xpZquTNikesB2YrCg0XiTfuJoVq8C7DQlhjVqsiM8c8kLgkkyXnA6xOIfvA+Sd7rPkcWPToFv5XIC4RUgp1N8tLH6Tbw/iDVu5B6zCX6vzQbn02257JIQ+hyzGcPia2c1F5li0YwCmmbJwbl405ID6Nv/6pPrI9nWU0qUj4wvnHzLdijoV8uZ6o0MCMacvsTMXSznQdfSgT+HtXZDjlgtz0v7v8LrA6Q1vwJgCVlvEtYeNxJtZXY84rmxsELgzewIe/DoOjtW3toS47U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
